### PR TITLE
Fix version picker

### PR DESCRIPTION
**Pull request by Stormheg**
~~Work in progress!~~

---

@tbrlpld: I am setting this to ready. 

---

Adds a layout override for the build of it's own docs. That layout override is adding the HTML that usually would be injected by READTHEDOCS. It also pulls in the script (which is not working for some reason) and the styles from READTHEDOCS. 

The actual fix is the SCSS component that overrides the RTD styles that for some reason do not work in our theme. 

If you want to preview the expanded version, add the `shift-up` class to the picker element. This is what the script would usually add. 

You can see that the script should work in this PR preview: https://wagtail--6930.org.readthedocs.build/en/6930/

### CODE REVIEW

**Comment by Stormheg** [comment]
There should be a read the docs sample version picker visible when developing locally now due to a template override I borrowed from [sphinx_rtd_theme](https://github.com/readthedocs/sphinx_rtd_theme/blob/master/docs/_templates/layout.html)

I haven’t completely fixed the version picker yet but documenting this in case I’m not able to continue working on this.

**Comment by tbrlpld** [comment]
Apparently they call it a the "Read the Docs flyout".

https://docs.readthedocs.io/en/stable/localization.html#project-with-multiple-translations

Apart from that little mention, I can not find any documentation on it though.

**Comment by tbrlpld** [comment]
Or they call it "versions menu" 

https://docs.readthedocs.io/en/stable/guides/remove-edit-buttons.html

**Comment by tbrlpld** [comment]
https://tech.michaelaltfield.net/2020/07/23/sphinx-rtd-github-pages-2/

**Comment by thibaudcolas** [comment]
I’m not sure if this helps but I put the Read the Docs build back together for this project so we could test with the real version picker: https://sphinx-wagtail-theme.readthedocs.io/en/latest/

This builds the `gh-pages` branch from GitHub, which is only updated after commits to `main` (whereas for PRs we have PR preview builds).

**Review by allcaps — APPROVED** [review]
I assume the commented code in `sass/_component_versionpicker_fix.scss` is to show what we did and did not customise.

I'm not sure about the commented code in Makefile. We might enable the rebuild... 

For now, I'm going to merge this and update the Wagtail PR to see it in action.

Thank you!

**Comment by thibaudcolas** [comment]
This is looking pretty spot-on judging by https://sphinx-wagtail-theme.readthedocs.io/en/latest/.

**Comment by tbrlpld** [comment]
Thanks @thibaudcolas and @allcaps for reviewing! 

Awesome that we can now view it in RTD before affecting Wagtails repo!

**Pull request merged**
