### PR TITLE
Update Node to version 18 & document usage of fnm

### LINKED ISSUE #187: Adopt Node 18 & fnm
* Node 18 can be migrated to now as it is more stable and about to be the LTS
* Move to `fnm` instead of `nvm` as the recommended node version manager (works on Windows & is faster)
* See equivalent Wagtail issue https://github.com/wagtail/wagtail/issues/8499

### PR DESCRIPTION
**Pull request by lb-**
- fnm is faster and has better Windows support
- node 18 is about to become the next LTS
- required webpack upgrade to support node 18 (crypto library change)
- resolves #187

### CODE REVIEW

**Comment by lb-** [comment]
ok not really sure on the problem here - may need some deeper investigation.

**Comment by lb-** [comment]
Setting to draft for now.

**Comment by allcaps** [comment]
> Since Netlify uses nvm to manage node versions, I wondered what was wrong with the build environment. As can be seen in the logs, the build environment was still running Ubuntu Xenial (16.04), which is no longer actively maintained.
> Thankfully, [Netlify allows you to select Ubuntu Focal (20.04)](https://docs.netlify.com/configure-builds/manage-dependencies/#build-image-defaults). To do so, navigate to _**Site settings > Build & deploy > Continuous Deployment > Build image**_ selection.
> I cleared the cache and it built and deployed perfectly this time.

https://lavaux.lv/2022/04/26/fix-netlify-build-errors-with-node-18.html

**Comment by lb-** [comment]
Thanks @allcaps - should I reach out on the core team for access to the Netlify instance? Or could you do this update?

**Comment by allcaps** [comment]
@lb- Netlify is updated. See core Slack. Can you give this PR a little kick?

**Comment by lb-** [comment]
Pushed but Vercel failed - not sure why (requested access on core team to view logs).

**Comment by lb-** [comment]
@allcaps  sorry the invite did not work - not sure what I am doing wrong with these computer things. I accepted the invite from the notification email but it kept saying 404 error.

I have just requested access to the Wagtail team in my Vercel account so maybe that will come up when you log in next.

Screen Shot 2022-11-09 at 7 20 49 am

**Comment by lb-** [comment]
Will mark as draft, not sure how to solve the Deployment issue.

**Pull request merged**
