### PR TITLE
added rst-content class to body

### LINKED ISSUE #131: rst-content styles are not being used
Our theme contains extensive customisations for content styling in https://github.com/wagtail/sphinx_wagtail_theme/blob/a056b6e941e6a9af4b2f32ab157ff95613a0ca55/sass/_component_rst.scss.

It looks like they aren’t being used on docs.wagtail.org, because nothing is outputting this `rst-content` class. Here is what it looks like when manually adding it:

rst-content

I’m not entirely sure whether us not using those styles is intentional or not. Our autodocs styles at least could use a bit more structure.

### PR DESCRIPTION
**Pull request by PaarthAgarwal**
I have added rst-content class to the main body. I couldn't test this change as I mentioned in https://github.com/wagtail/sphinx_wagtail_theme/issues/20#issuecomment-1082674659 but I believe it should fix #131.

### CODE REVIEW

**Comment by PaarthAgarwal** [comment]
Throwing the same error as I got while building docs. I believe it's happening because jinja2 has replaced `contextfunction `with `pass_context`.
Reference: https://stackoverflow.com/a/71634495

**Comment by PaarthAgarwal** [comment]
I found a PR that replaces the deprecated `contextfunction` with `pass_context` https://github.com/wagtail/wagtail/pull/8203.

**Review by lb- — APPROVED** [review]
Looking great @PaarthAgarwal 
the build issue should be resolved via this PR once merged https://github.com/wagtail/sphinx_wagtail_theme/pull/142

I checked your change locally and this does the job nicely, thank you.

**Comment by lb-** [comment]
Hey @PaarthAgarwal - hopefully the changes in 142 will help but if you get stuck maybe reach out on `#support` in slack and myself or someone might be able to help (feel free to ping me in Slack)

**Pull request merged**
