### PR TITLE
Remove jQuery loading by default

### LINKED ISSUE #250: JavaScript broken with Sphinx 6
Sphinx 6 removed jquery, and it seems our theme is still using it, hence JavaScript functionality, such as the search, is broken if the docs are built using Sphinx 6.

I would recommend we also remove jquery, since I don't think we are using it very much; however as a quick fix there is an official sphinx jquery plugin. See: https://www.sphinx-doc.org/en/master/changes.html#id42

I will look into doing this, once I have some free time.

### PR DESCRIPTION
**Pull request by lb-**
- Sill used as a peer dependency of Bootstrap
- Core jQuery dependency removed though
- Fixes #250

### CODE REVIEW

**Comment by lb-** [comment]
@vsalvino  is this what you were thinking?

Note: I have not dug into JS usage of bootstrap, it appears we are not really using anything but I have left it importing in `theme.js` (the bootstrap import).

At least we can see a deployment and have a look.

**Comment by vsalvino** [comment]
That should do it. I think the only bootstrap JS feature we may be using is the mobile menu... does that still work correctly with this change?

**Comment by vsalvino** [comment]
P.S... bootstrap 5 did remove jquery as a dependency. Not sure how broken that would be to upgrade, or if it would be a mostly drop-in replacement given our minimal bootstrap usage. https://getbootstrap.com/docs/5.2/migration/

**Comment by lb-** [comment]
The mobile menu expander works fine in the build but it could be driven by the peer dep. 

Yeah maybe BS 5 is an option. 

I might not get the chance to look at this one again for a bit though

**Comment by vsalvino** [comment]
I think this looks good then. I'll look into Bootstrap 5 when I get a chance.

**Review by vsalvino — APPROVED** [review]

**Comment by lb-** [comment]
Bootstrap 5 discussion moved to a new issue https://github.com/wagtail/sphinx_wagtail_theme/issues/254

**Pull request merged**
