### PR TITLE
Deemphasised toc text

### LINKED ISSUE #20: Deemphasize "page content" navigation font
Based on https://github.com/wagtail/wagtail/issues/6793

>  Consider going a bit less black with the Page contents section, to make it less distracting and indicate that it’s ‘secondary’ content

I guess something like a lighter font color could be good. This should be revised after the design proposal is implemented (see #10 )

Ref, we decreased the font size here, it works pretty well. https://wagtail--6792.org.readthedocs.build/en/6792/getting_started/tutorial.html

### PR DESCRIPTION
**Pull request by PaarthAgarwal**
Fixes #20.
Screenshot from 2022-04-10 00-19-00

### CODE REVIEW

**Comment by tbrlpld** [comment]
I am afraid this one has side effects for the main toc (on the left side). We would only want to reduce the "page toc" style on the right side.

**Comment by PaarthAgarwal** [comment]
> I am afraid this one has side effects for the main toc (on the left side). We would only want to reduce the "page toc" style on the right side.

Hmm🤔

**Comment by PaarthAgarwal** [comment]
The bigger picture
image

**Comment by tbrlpld** [comment]
> The bigger picture
> image

Check out the rule you are using. It contains the `li:not(.toctree-l1)`. This has only effects in the main toc on levels lower than the top level. When you open the "Examples" you will see those are gray too.

**Comment by PaarthAgarwal** [comment]
> > The bigger picture
> > image
> 
> Check out the rule you are using. It contains the `li:not(.toctree-l1)`. This has only effects in the main toc on levels lower than the top level. When you open the "Examples" you will see those are gray too.

You won🏳️🏳️

**Comment by PaarthAgarwal** [comment]
Closing in favor of #159.
Gg @tbrlpld

**Pull request closed without merging**
