### PR TITLE
Chore 5: Cleanup layout

### LINKED ISSUE #5: Clean up layout.html
`sphinx_typo3_theme/layout.html` is the 'base template' and contains things we don't want/need:

- [x] Typo3 specific headers / footers / blocks
- [x] Vanilla CSS, we should use Bootstrap
- [x] Redundant comment (all comments)
- [ ] Head should at least have the current RTD-theme features

Let us keep this issue as meta-issue and open multiple

### PR DESCRIPTION
**Pull request by tbrlpld**
Addressing the issues outlined in #5 

Closes #5 #10 #26 #41

Partially addresses #10

### CODE REVIEW

**Comment by tbrlpld** [comment]
@thibaudcolas @allcaps I think this is ready for review. It is still not perfectly matching the design, but I would leave that for future smaller PRs. This clean up is already getting pretty big.

**Comment by tbrlpld** [comment]
@allcaps I did not know what all the features are you where referencing in #5 with

> Head should at least have the current RTD-theme features

I have tried to only remove obvious Typo3 related things from the head and hope that all the features are still available.

**Comment by tbrlpld** [comment]
For some reason, the [Workflows page](https://deploy-preview-52--sphinx-wagtail-theme.netlify.app/workflows.html) does not look right. Since it is the only page, I assume that is has something todo with the content. 

I would leave that until we add our own example pages to develop the components. 

That would also be the time I would suggest to remove/change the existing Sphinx component overrides.

**Comment by Morsey187** [comment]
Hi @tbrlpld, 
If this is any help, the Workflows page issue, looks to be related to `<pre>` elements inside of a flex item, See  https://stackoverflow.com/questions/49259598/flex-item-with-pre-content-not-shrinking

Adding `overflow: auto;` to the main and article elements seems to help however it doesn't look to be a complete fix. This issue seems to have been introduced in this commit [Simplify TOC ordering](https://github.com/wagtail/sphinx_wagtail_theme/pull/52/commits/7073fe2f247f8e452bd6adcfc31eacc8ab2b7e84)

**Comment by Stormheg** [comment]
Heads up: I have removed the workflows page in https://github.com/wagtail/sphinx_wagtail_theme/pull/57 because I don't think we need it now that the CI setup is simplified.

**Comment by tbrlpld** [comment]
> Hi @tbrlpld, 
> 
> If this is any help, the Workflows page issue, looks to be related to `<pre>` elements inside of a flex item, See  https://stackoverflow.com/questions/49259598/flex-item-with-pre-content-not-shrinking
> 
> 
> 
> Adding `overflow: auto;` to the main and article elements seems to help however it doesn't look to be a complete fix. This issue seems to have been introduced in this commit [Simplify TOC ordering](https://github.com/wagtail/sphinx_wagtail_theme/pull/52/commits/7073fe2f247f8e452bd6adcfc31eacc8ab2b7e84)

Oh, awesome. Thanks for digging @Morsey187

**Comment by tbrlpld** [comment]
@Morsey187 Let's fix that in #69

**Comment by allcaps** [comment]
> @allcaps I did not know what all the features are you where referencing in #5 with
>> Head should at least have the current RTD-theme features

I mean that the `<head>` contents is often overlooked. We should make sure we don't loose needed metadata, scripts or analytics. So we need to diff the head of https://wagtail--6930.org.readthedocs.build/en/6930/index.html with the head of https://docs.wagtail.io/en/latest/

I'll do that.

**Review by allcaps — APPROVED** [review]

**Pull request merged**
