### PR TITLE
Chore: Update latest changes in history

### PR DESCRIPTION
**Pull request by tbrlpld**
Adds the last couple of merged PRs to the History.

### CODE REVIEW

**Comment by Scotchester** [comment]
Let's hold on this PR until the other open ones are merged, as well.

**Comment by vsalvino** [comment]
Good idea... I'll be keeping 'em coming for a while... until I get my project to finally work with this theme!

**Comment by tbrlpld** [comment]
@Scotchester @vsalvino My idea was to put the burden of updating the changelog onto the PRs themselves. I guess that should be documented somewhere though. And I guess we have to double check before a release anyhow. So I am happy keep this going as you two are currently proposing.

**Comment by Stormheg** [comment]
Agreed, updating the changelog before/after merging a PR should definitely be prominently documented.

**Comment by tbrlpld** [comment]
I think it is not necessary to keep this issue around

**Comment by tbrlpld** [comment]
Whoops... this is a PR and not an issue 🤦‍♂️

**Comment by lb-** [comment]
Have incorporated into https://github.com/wagtail/sphinx_wagtail_theme/pull/141
Note: Used en GB spelling as per other Wagtail packages docs

**Comment by allcaps** [comment]
This landed via https://github.com/wagtail/sphinx_wagtail_theme/pull/141

**Pull request closed without merging**
