### PR TITLE
Make navigation sticky

### PR DESCRIPTION
**Pull request by DanielSwain**

### CODE REVIEW

**Comment by tbrlpld** [comment]
**Question:** How does this behave on small screens?

**Comment by DanielSwain** [comment]
@tbrlpld To answer your question, I've checked using the developer tools in the browser, and it behaves fine.  On smaller devices where the mobile menu appears, the navigation starts out at the top, and you can scroll down the page past the navigation and through the page content.  The behavior of the navigation on smaller devices (at both orientations) is exactly the same with or without the `sticky-top` class requested in the PR.

**Comment by DanielSwain** [comment]
@tbrlpld Anything more needed from me in order to have this PR approved?

**Comment by tbrlpld** [comment]
@DanielSwain Looks good to me (just tried it locally)

**Pull request merged**
