### PR TITLE
Distinguished figure caption

### LINKED ISSUE #161: Figure caption is hard to distinguish from body text
The caption text is styled the same as the body text. This makes for a confusing reading experience.

We should come up with a style that distinguishes the caption text visually from the body text. Also, it would be more readable to have a bit of whitespace between the figure and the image. 

Also, it looks odd to me that the figure text is wider than the image/figure. 

image

This may be a good place to reuse the gray from the page content TOC.

image

### PR DESCRIPTION
**Pull request by PaarthAgarwal**
Distinguished the caption text visually from the body text and added a bit of whitespace between the figure and the image.

After the fix:

image

Fixes #161.

### CODE REVIEW

**Comment by tbrlpld** [comment]
Thanks @PaarthAgarwal love his is looking nice. Thank you!

**Comment by PaarthAgarwal** [comment]
Glad that you liked it😄
Also, this happens to be my 20th PR in Wagtail. Cheers!

**Comment by lb-** [comment]
yay congrats!

**Comment by PaarthAgarwal** [comment]
> yay congrats!

Thanks, LB!🎉

**Pull request merged**
