### PR TITLE
Monospace font added for the names

### PR DESCRIPTION
**Pull request by msaini0r**
## Description

Monospace font added for the names

issue - #243

### CODE REVIEW

**Comment by salty-ivy** [comment]
@msaini0r it would be better to add some, screen shots to show before and after changes

**Comment by msaini0r** [comment]
> @msaini0r it would be better to add some, screen shots to show before and after changes

## Before



## After

**Review by laymonage — COMMENTED** [review]
I don't see any difference, I think we're not looking at the right thing here :)

FYI check with the model reference docs, the class and attribute names should use a monospace font.

image

**Comment by laymonage** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
