### PR TITLE
Main nav made scrollable

### LINKED ISSUE #176: Scroll issues on long table of content
When the table of content is longer than the view port, you can not scroll the table of content independently of the page. 

https://user-images.githubusercontent.com/24797493/170080033-7d0134c8-3eea-4a30-8328-d6703fa25cc2.mov

I believe this is cause by the overall structure of our base layout. I am not sure what the best solution is here, but I think we need to adjust the design a bit. I think this is not going to be able to be combined with the footer stretching the full width.

### PR DESCRIPTION
**Pull request by PaarthAgarwal**
Fixes #176.

### CODE REVIEW

**Comment by tbrlpld** [comment]
Looks good to me! Thanks for the quick fix @PaarthAgarwal!

I think there might be an opportunity to restructure the overall layout a little to make this behaviour feel a bit more "solid", but this is a great fix.

**Comment by PaarthAgarwal** [comment]
Glad you liked it!

**Comment by PaarthAgarwal** [comment]
Does it need a changelog entry?

**Comment by lb-** [comment]
> Does it need a changelog entry?

I think the existing changelog entry covers it, this is just a refinement on the move to sticky TOC

**Pull request merged**
