### PR TITLE
Add version styles to match admonitions

### PR DESCRIPTION
**Pull request by vsalvino**
image

Also added all the admonitions to the example page, just to test that they looked good.

### CODE REVIEW

**Review by Scotchester — CHANGES_REQUESTED** [review]
Not the fault of this PR, but seeing the screenshot prompted me to check the contrast in those boxes, and it turns out that the [white-on-red combo does not have sufficient contrast](https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=D9534F). Using that tool's lightness slider, looks like shifting the red background to [`#d4403a` would do the trick](https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=D4403A).

**Comment by Scotchester** [comment]
Sidenote: Color perception is a funny thing. The combo that prompted me to check it was the blue one! Looking forward to [this new color contrast model](https://www.myndex.com/APCA/simple) getting more widely adopted. For extra credit, you could test all of the combos against that.

**Comment by vsalvino** [comment]
I was thinking the same thing regarding contrast. Didn't want to move anyone's cheese. I also find the black on blue a bit odd looking.

Since those are all sass variables, it might warrant a separate PR to change them to meet contrast guidelines.

**Comment by Scotchester** [comment]
Fair enough :)

**Review by Scotchester — APPROVED** [review]

**Pull request merged**
