### PR TITLE
Sphinx v4: use js files included with sphinx; fix documentation_options

### PR DESCRIPTION
**Pull request by vsalvino**
Sphinx 1.8 moved `DOCUMENTATION_OPTIONS` from the theme templates into a JavaScript template. Sphinx 4 then started adding the JavaScript template into `script_files`, causing a 404 when built with Sphinx 4.

Since sphinx_wagtail_theme does not inherit from a built-in sphinx theme, it never received the `documentation_options.js` file upstream (from the base theme). Therefore that file was `404`-ing, and some of the newer DOCUMENTATION_OPTIONS were missing.

This change switches the theme to inherit from Sphinx's `basic` theme, which means we now get all the glorious JS files directly from sphinx rather than providing our own copies (which were taken from some unknown version of sphinx). This will also prevent the theme from diverging from Sphinx functionality (i.e. search) over time.

See: https://www.sphinx-doc.org/en/master/changes.html?highlight=documentation_options#id35

### CODE REVIEW

**Comment by Scotchester** [comment]
> Alternatively, we could drop support for sphinx older than 4, if this comes across as too hacky.

I wouldn't call it too hacky, but seeing as Sphinx 4 came out six months ago now, I would be fine with dropping support for it in the next release of this theme.

**Comment by vsalvino** [comment]
Yea, generally themes will inherit from "basic" so as to automatically get whatever that version of sphinx provides. Since we are not inheriting we will want to keep an eye on the basic theme changes with each major release of sphinx, to remain compatible. That being said, converting the theme to inherit from basic is probably not a chore anyone wants to do unless it becomes necessary.

I also know that Read the Docs tends to encourage people to pin some ancient version of sphinx (1.8.5) because that is their default if you don't specify. You can use newer versions with RTD but have to specify it in requirements.txt. So that is something to consider. Sphinx does have a mechanism for a theme to require a specific version and refuse to build on older versions, if it comes down to it. Which might be the path of least resistance.

**Comment by Scotchester** [comment]
> Sphinx does have a mechanism for a theme to require a specific version and refuse to build on older versions, if it comes down to it. Which might be the path of least resistance.

This seems reasonable to me, too.

**Comment by vsalvino** [comment]
Upon further looking into it... I think a lot of the other javascript files (search, jquery, doctools, etc.) are all "hard-coded" in this theme, from whatever version of sphinx they were originally copied from. I might do a bit more investigation to see if we can truly inherit from the basic theme, as recommended by sphinx, which will make all of these concerns mostly go away.

**Comment by vsalvino** [comment]
Ok - just made another push. I removed the js file which were copied from (unknown version) of sphinx. Change the theme config to inherit from the basic theme.

So now, js files (or anything else which is not included in our theme) will automatically come directly from whatever version of sphinx the user has installed. This should greatly reduce any compatibility issues between sphinx versions, and maintenance burden.

I tested this on the included `/docs/`, and also on my project's docs, each works cleanly with no errors. I would like to test this with something deployed to Read The Docs, and also wagtail's docs, to err on the side of caution.

Also tested with Sphinx version 1 and 4. Works in both.

**Comment by vsalvino** [comment]
To help test, I have created a build of a custom project using all my open PRs merged together: https://vince-temp.codered.cloud/

**Comment by vsalvino** [comment]
@tbrlpld could I get a quick review/approval to merge this in?

**Comment by lb-** [comment]
@vsalvino  looks good to me, merging in

**Pull request merged**
